var dinner =[
    {
    "key":"DINNER01","category":"Dinner","name":"Healthy Meal Plane", "about":"How we Dream about our future", "price":22.99, "stock":12, "img":"https://i.ibb.co/1GBqd7C/dinner1.png","url":"https://ibb.co/1GBqd7C", "description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]
    },
    {"key":"DINNER02","category":"Dinner","name":"Fried Chicken Banto", "about":"How we Dream about our future", "price":9.99, "stock":16, "img":"https://i.ibb.co/X4XBQyY/dinner2.png", "url":"https://ibb.co/X4XBQyY","description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]
    },
    {"key":"DINNER03","category":"Dinner","name":"Tarragon Rubbed Salmon", "about":"How we Dream about our future", "price":6.99, "stock":6, "img":"https://i.ibb.co/C1DckTg/dinner3.png","url":"https://ibb.co/C1DckTg", "description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]
    },
    {"key":"DINNER04","category":"Dinner","name":"Indian Lunch", "about":"How we Dream about our future", "price":8.99, "stock":11, "img":"https://i.ibb.co/m4ZDSWh/dinner4.png","url":"https://ibb.co/m4ZDSWh", "description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]
    },
    {"key":"DINNER05","category":"Dinner","name":"Beef Steak", "about":"How we Dream about our future", "price":15.99, "stock":31, "img":"https://i.ibb.co/WzM6P2k/dinner5.png", "url":"https://ibb.co/WzM6P2k", "description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]
    },
    {"key":"DINNER06","category":"Dinner","name":"Hanny Soy Glazed Salmon with Peppers","stock":48,"price":39.99,"about":"How we Dream about our future","img":"https://i.ibb.co/nRC98mv/dinner6.png","url":"https://ibb.co/nRC98mv","description":"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.","features":[{}]}
    
];
    export default dinner;